#! /usr/bin/env bash
./bin/start.sh ./bin/socket-command --command 'log/write' --data='{"logName":"pants","key":"one"}'
./bin/start.sh ./bin/socket-command --command 'log/read' --data='{"logName":"pants"}'
